language: node_js
node_js:
- stable
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- .ci/lerna.sh
script:
- npm run publish -- --git-remote=ci
env:
  global:
  - secure: iggRjI6lW75twJFRy4ZTzZI94A3+7/6dr2GkPc+ejCqP1eGYlVQ5uFlsid9/Qu+CwkttxYI4PTo8z8ovEl734oSZ8LFbLC4oZRQUEqDvGwjJXQgS1X4vgEYgTLnv0OlPnGG+g7tid8JOpt9j7niatq+3JZbbSK85lNr3bWM+aPDs5vYcOPA/MM0ryk5dgnKpeGpUjnpqqnIobD0aEJr3ViJhM+Rn7gesSyb7XH0opPqlNrFsEHiWZ8LjMkqURHeMzl24ljBYjLpr1nXeBi/Q4Iv/6ntPsv7m+d6MrfbQbhOXMjorwEyrEkQlnN+ENXsoqZw61Lu6TpIIC+397qQlSeD4VnSTNCmTmwXZuf8N5CnY8R3IgXyFTOA7kfd0fEV+gz1iY4Aqbz2qZDFlEvMoCPUBDp8XU426ZTT4VCj9a2tVBFGfx8Ih2sYLM3CNBy2Vie8maHRHwil4+KGkXfvwvSdXuzbkh/qG8nTkioW/DgjgKQ81Z8FEvPefT69sVEpE7iTpWc/Hff/8KXg4Sfgd87LPwzwG2I+O3MDVjfXQiZ0WMXlwJjJTOQGLXHG6cd8ACfoc4x5cTOFzqRBGEqsGURgThPNGzUoWlyZ/WtkI1nNMCzrbCYYsMtW8LKWxTx2r083B58be+SRGt5ZYRyLy+myIw/XZ0wkP+yjrOstzvzI=
  - secure: b+yRrOlgEmOmasKW0iUu6lCRDzs5Dlomka2LVYqdTxzzHIP8TdF+sJ5HayxaBlHFHu5oOfTIS38rzrFbB5F78kfR9NgM5fTLrVXP9s0FoUPPVU+VLLaBPktkYNMl8He7yMJcMVDuZK4vLSuKjnsOzmecswOWnuQcQsdvFZ6uXUYILZQRH6Ea1/8yVdC+coveSslxafhkiuxiJjtJBAvGqktPZ4BMmmzTalQOYaEfCO7y/IHTkPTe65tuX067B53Yo1sosFw2WqWhG4Bx6VV+EmoqGWWHeqaS2kzjlKvfXq0dSLvTNNISkMCLegkNx1vXKRaUAAsXXHsLgDRyt/CgKLON2dcL9Hb+rp4n/NXJCG463vHzSas1q2WxM9g1pCgPBug4bS/uiXh8BJKyJPT2NENEAGLzFOLJ8KFE+zDcHpVJhnjJgF1MRh4QJOzJD0GqRxmjBy6jJ06P8nvCiCfOBZIafogpmvXZCQ7XyJ2jmKRwvleUBQLiM7tMR7M99d/Pl8JpipC32dPDQPmrtz5WIjDHZZSmyS/zWbxmF/mAIU9T/TC6uWVOMlUOr2rafcbRBe80sZASDNTyKXlpNf0YY93eRFyf77yW1iZRVz09C80GFDhPUBpKDrePgDVvjUo0kc8OjbAodjiAEfYSvTiqcyyMuMZqGMrS7Y1MsCiLl8A=
